idf_component_register(
    SRCS
        "main.c"
        "config.c"
        "runtime_settings.c"
        "bridge.c"
        "Drivers/CAN/can_driver.c"
        "Drivers/RS485/rs485_driver.c"
        "Operation_Modes/can_forward_sniffer.c"
        "Operation_Modes/rs485_forward_sniffer.c"
        "CAN_Decoder.c"
        "modbusDecoder.c"
        "rs485_can_bridge.c"
        "BMS_Protocols/Pylon/pylon_rs485_bridge.c"
        "Web_interface/web_interface.c"
        # "modbusResp.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        driver
        esp_timer
        esp_http_server
        esp_wifi
        esp_netif
        nvs_flash
)
